### ISSUE TITLE
Fix: 결제페이지 QA 반영 

### ISSUE THREAD

**Issue by jongsujin** [Yanol-Market/frontend#111]
## ☘️ Description
결제페이지 QA 반영 

## ☘️ Todo

- [ ] 결제페이지 QA 반영 
- [ ] 결제페이지 모바일 구현
- [ ] 채팅방 생성 데이터 전달
