### ISSUE TITLE
Fix: 상품 등록/ 나의 거래 QA 반영

### ISSUE THREAD

**Issue by moonyah** [Yanol-Market/frontend#151]
## ☘️ Description
- 상품 등록 완료시에 상품 상세 페이지에서 뒤로 가기 버튼 눌렀을때 상품 등록으로 가는거 -> 홈화면으로 가도록 수정
-  비로그인 시, 상품 등록/ 나의 거래 눌렀을 때 signin에서 뒤로 가기 누르면 -> 홈화면으로 안 가는 문제 해결하기
- 야놀자 로그인 페이지 내 뒤로 가기 버튼 추가
- 상품 등록 과정 중 야놀자 로그인 페이지 아이디 또는 비밀번호 오기입 시 “이메일 또는 비밀번호를 확인해주세요” 문구 노출

## ☘️ Todo
- [x] 비로그인 시, 상품 등록/ 나의 거래 눌렀을 때 signin에서 뒤로 가기 누르면 -> 홈화면으로 안 가는 문제 해결하기 => replace 옵션 추가로 해결!!
- [x] 야놀자 로그인 페이지 내 뒤로 가기 버튼 추가
- [x] 상품 등록 과정 중 야놀자 로그인 페이지 아이디 또는 비밀번호 오기입 시 “이메일 또는 비밀번호를 확인해주세요” 문구 노출
- [x] /myaccount -> /myaccount/registration로 가서 등록을 하면 /myaccount로 가고 그 곳에서 뒤로가기를 하면 /myaccount/registration로 가는 문제 => navigate('/myaccount');를 navigate(-1);로 변경해서 해결
- [x] 상품 등록 완료시에 상품 상세 페이지에서 뒤로 가기 버튼 눌렀을때 상품 등록으로 가는거 -> 홈화면으로 가도록 수정
/addproduct/* -> /product/* 로 갈 경우 뒤로 가기를 하면 /으로 가야 하는데 /addproduct/*으로 가는 문제 해결하기 => 상품 상세 페이지에서 "판매 중인 상품 목록 가기"로 변경됨
