### ISSUE TITLE
Fix: 관심 지역 바텀시트 스크롤화 및 찜한 상품 상태값 보여주기 구현

### ISSUE THREAD

**Issue by jongsujin** [Yanol-Market/frontend#159]
## ☘️ Description
관심 지역 바텀시트 스크롤화 및 찜한 상품 상태값 보여주기 구현

## ☘️ Todo

- [ ] 코드 리팩토링
- [ ] console.log 제거 
- [ ] 마이페이지 찜한 상품 상태값 보여주기
- [ ] 관심지역 바텀시트 스크롤화 

## ☘️ ETC
마지막 PR이길..!
