### ISSUE TITLE
Feat: 마이페이지 페이지 연결 및 디자인 수정

### ISSUE THREAD

**Issue by jongsujin** [Yanol-Market/frontend#28]
## ☘️ Description
마이페이지별로 페이지 연결 후 퍼블리싱 하고 난 뒤 놓쳤던 css 부분들 수정할 계획입니다. 

## ☘️ Todo

- [ ] 마이페이지 페이지 연결
- [ ] 놓쳤던 CSS 부분들 수정
- [ ] 테스트코드 작성
- [ ] 중복된 페이지 공통 컴포넌트화
