### ISSUE TITLE
Feat: 상품 등록 페이지 퍼블리싱 개선

### ISSUE THREAD

**Issue by moonyah** [Yanol-Market/frontend#67]
## ☘️ Description
상품 등록 페이지 api 연결 전 퍼블리싱 개선

## ☘️ Todo

(1) 상품 선택 단계
- [x] 비활숙소 CSS 추가
- [x] 여러 개 선택 불가
- [x] 선택 시, 다음 버튼 활성화
- [x] 숙소 정보 세로선으로 나누기
- [x] 체크인일 기준으로 오름차순 정렬

(2) 상품 정보 입력 단계
- [x] 글자 수 500자 제한 
- [x] 입력 금액 제한
- [x] 필수 정보 입력 시, 다음 버튼 활성화

+) 나의 거래 페이지
- [x] 빨간점 ui 추가
## ☘️ ETC
