### ISSUE TITLE
Feat: 상품 등록 페이지 스타일 수정

### ISSUE THREAD

**Issue by moonyah** [Yanol-Market/frontend#82]
## ☘️ Description
나의 거래 페이지 api 연동

## ☘️ Todo
- [x] 상품 등록 - 판매자 한마디 textarea css 수정
- [x] 상품 등록 - 약관 등록 부분 css 수정
- [x] 상품 등록 - 완료 페이지 부분 css 수정
- [x] 상품 등록 - 판매 정보 입력 부분 기존 구매가 관련 문구 추가
- [x] 상품 등록 - utils 사용해서 코드 정리
- [x] 나의 거래 - 마지막 채팅 시간 표시 변환 (효주님께서 수정 예정)
